-- Initial schema for AquaGas Premium
-- Run this in Supabase SQL editor

-- Users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text,
  name text not null,
  role text not null check (role in ('admin', 'wholesale', 'retail')),
  phone text default '',
  address text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  icon text default 'Package',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint not null references categories(id),
  retail_price numeric not null,
  wholesale_price numeric not null,
  stock integer not null default 0,
  min_wholesale_qty integer not null default 1,
  unit text default 'unit',
  status text default 'Tersedia' check (status in ('Tersedia', 'Menipis', 'Kosong')),
  image text default '',
  description text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Orders table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  user_id bigint not null references users(id),
  status text default 'pending' check (status in ('pending', 'processing', 'completed', 'cancelled')),
  total_amount numeric not null,
  payment_method text default 'cod' check (payment_method in ('cod', 'transfer')),
  payment_status text default 'unpaid' check (payment_status in ('unpaid', 'paid', 'refunded')),
  notes text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Order items table
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id),
  product_id bigint not null references products(id),
  quantity integer not null,
  price numeric not null,
  subtotal numeric not null,
  created_at timestamp with time zone default now()
);

-- Refill suppliers table
create table if not exists refill_suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text default '',
  address text default '',
  contact_person text default '',
  is_active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Refill schedules table
create table if not exists refill_schedules (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references refill_suppliers(id),
  product_id bigint not null references products(id),
  schedule_date date not null,
  estimated_time text default '',
  quantity integer not null default 0,
  status text default 'direncanakan' check (status in ('direncanakan', 'dalam_perjalanan', 'selesai', 'dibatalkan')),
  notes text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Settings table
create table if not exists settings (
  key text primary key,
  value text default ''
);

-- Guest visits table
create table if not exists guest_visits (
  id bigint generated by default as identity primary key,
  ip_address text default '',
  user_agent text default '',
  path text default '',
  visited_at timestamp with time zone default now()
);

-- Enable Row Level Security (after tables are created)
alter table users enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table refill_suppliers enable row level security;
alter table refill_schedules enable row level security;
alter table settings enable row level security;
alter table guest_visits enable row level security;

-- RLS Policies

-- Admin/service role can view all users (needed for login flow)
create policy "Admin can view all users"
  on users for select
  using (auth.jwt() ->> 'role' = 'admin' or auth.role() = 'service_role');

-- Admin can update users
create policy "Admin can update users"
  on users for update
  using (auth.jwt() ->> 'role' = 'admin' or auth.role() = 'service_role');

-- Everyone can view categories
create policy "Categories are public"
  on categories for select
  using (true);

-- Everyone can view available products
create policy "Products view for all"
  on products for select
  using (true);

-- Admin can manage products
create policy "Admin can manage products"
  on products for all
  using (auth.jwt() ->> 'role' = 'admin');

-- Users can view their own orders
create policy "Users can view own orders"
  on orders for select
  using (auth.uid()::text = (select email from users where id = user_id));

-- Admin can view all orders
create policy "Admin can view all orders"
  on orders for select
  using (auth.jwt() ->> 'role' = 'admin');

-- Everyone can view settings
create policy "Settings are public"
  on settings for select
  using (true);

-- Seed data

-- Insert categories
insert into categories (name, slug, icon) values
  ('Air Galon', 'air-galon', 'Droplets'),
  ('Gas Elpiji', 'gas-elpiji', 'Flame'),
  ('Air Mineral', 'air-mineral', 'Droplets'),
  ('Isi Ulang', 'isi-ulang', 'RotateCcw')
on conflict (slug) do nothing;

-- Insert settings
insert into settings (key, value) values
  ('store_name', 'AquaGas Premium'),
  ('store_phone', '0812-3456-7890'),
  ('store_address', 'Jl. Merdeka No. 123, Jakarta Selatan'),
  ('store_email', 'info@aquagaspremium.com'),
  ('shipping_cost_per_km', '5000'),
  ('free_shipping_minimum', '100000'),
  ('payment_cod_enabled', 'true'),
  ('payment_transfer_enabled', 'true')
on conflict (key) do nothing;

-- Insert products
insert into products (name, category_id, retail_price, wholesale_price, stock, min_wholesale_qty, unit, status) values
  ('Galon Aqua 19L', 1, 21000, 18000, 45, 10, 'unit', 'Tersedia'),
  ('Galon Le Minerale 19L', 1, 20000, 17000, 30, 10, 'unit', 'Tersedia'),
  ('Galon VIT 19L', 1, 19000, 16000, 20, 10, 'unit', 'Tersedia'),
  ('Gas Elpiji 3kg', 2, 18000, 15500, 22, 5, 'tabung', 'Tersedia'),
  ('Gas Elpiji 5.5kg', 2, 95000, 88000, 15, 5, 'tabung', 'Tersedia'),
  ('Gas Elpiji 12kg', 2, 190000, 175000, 8, 5, 'tabung', 'Menipis'),
  ('Air Mineral 600ml (Karton)', 3, 35000, 30000, 30, 10, 'karton', 'Tersedia'),
  ('Air Mineral 1500ml (Karton)', 3, 45000, 38000, 5, 10, 'karton', 'Menipis'),
  ('Air Mineral 330ml (Karton)', 3, 30000, 25000, 25, 10, 'karton', 'Tersedia'),
  ('Isi Ulang Air Galon', 4, 5000, 4000, 100, 20, 'galon', 'Tersedia');

-- Note: Users with passwords should be created via Supabase Auth